config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process for Passenger Standalone.
  mount ActionCable.server => "/cable"

  root "recipes#index"

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :recipes, only: [ :index, :new, :create ] do
    collection do
      get :search
      post :import
      get :choice
      get "import_status/:id", action: :import_status, as: :import_status
    end
  end

  scope "/recipes/:username", as: :user, controller: :recipes do
    resources :recipes, only: [ :show, :edit, :update, :destroy ], path: "", param: :slug do
      resources :reviews, only: [ :show, :create, :edit, :update, :destroy ]
      resources :recipe_images, only: [ :new, :create, :destroy ]
      member do
        get :log_in
        get :likes
      end
    end
  end

  resources :categories do
    collection do
      get :more
    end
  end

  resources :users, only: [ :index, :show, :edit, :update, :destroy ] do
    member do
      get :log_in
      get :followers
      get :following
    end
  end

  resources :favoritisms, only: [ :create, :destroy ]

  resources :relationships, only: [ :create, :destroy ]

  resources :notifications, only: [ :index ] do
    collection do
      patch :mark_as_read
      get :settings
      patch :update_settings
    end
  end

  resources :push_subscriptions, only: [ :create, :destroy ] do
    collection do
      get :vapid_public_key
    end
  end

  get "sitemap.xml", to: "sites#sitemap", format: :xml

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save :set_slug
  before_destroy :reassign_content_to_admin
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  # Is following users relationships.
  has_many :relationships, dependent: :destroy
  has_many :following, through: :relationships, source: :followed
  # Followed by users relationships.
  has_many :reverse_relationships, foreign_key: "followed_id",
    class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :user

  has_many :favoritisms, dependent: :destroy
  has_many :recipes, through: :favoritisms

  has_many :categories
  has_many :recipes
  has_many :reviews, dependent: :destroy
  has_many :imports, dependent: :destroy
  has_many :push_subscriptions, dependent: :destroy

  has_one :info, dependent: :destroy
  accepts_nested_attributes_for :info, reject_if: :all_blank, allow_destroy: true

  has_many :notifications, foreign_key: "recipient_id", dependent: :destroy
  has_one :notification_setting, dependent: :destroy

  has_one_attached :avatar, dependent: :purge_later

  attr_accessor :remove_avatar

  validates :username, presence: true, uniqueness: true

  default_scope { order(username: :asc) }
  # Finds users who received a notification about the notifiable.
  scope :by_notified, ->(notifiable) {
    includes(:notifications).where(notifications: { notifiable_id: notifiable })
  }
  # Finds users who did not receive a notification about the notifiable.
  scope :by_unnotified, ->(notifiable) { where.not(id: by_notified(notifiable)) }
  # Finds users who uploaded an image to a recipe, owns the recipe and reomves the notifier user.
  scope :by_uploaders, ->(notifiable) {
    uploaders = notifiable.recipe.recipe_images.map(&:user) << notifiable.recipe.user
    where(id: uploaders).where.not(id: notifiable.user)
  }
  # Finds users who reviewed a recipe, owns the recipe and removes the notifier user.
  scope :by_reviewers, ->(notifiable) {
    reviewers = notifiable.recipe.reviews.map(&:user) << notifiable.recipe.user
    where(id: reviewers).where.not(id: notifiable.user)
  }
  # Only email users that want to be.
  scope :recipients_email, ->(notifiable) { receive_email(notifiable).remove_recently_unread.map(&:email) }
  # Check users notification settings.
  scope :receive_email, ->(notifiable) {
    includes(:notification_setting).where(notification_settings: { id: nil }).
    or(includes(:notification_setting).where(notification_settings: { receive_email: true }).
    where(notification_settings: { receive_notification_type(notifiable) => true }))
  }
  # Finds all users that have received notifications that are unread in the past week.
  scope :by_recently_unread, -> {
    time_range = Time.current.beginning_of_day..Time.current.end_of_day
    includes(:notifications).where(notifications: { created_at: time_range }).
    where(notifications: { is_read: false })
  }
  # Remove any users that were recently notified.
  scope :remove_recently_unread, -> { where.not(id: by_recently_unread) }

  def info
    super || build_info
  end

  def find_favoritism(recipe)
    favoritisms.find_by(recipe: recipe)
  end

  def favorite_recipes
    favoritisms.map(&:recipe)
  end

  # Use :slug in params instead of :id
  def to_param
    slug
  end

  def following?(user)
    relationships.find_by(followed: user)
  end

  def mark_as_read
    # Mark notifications as read.
    notifications.by_unread.mark_as_read

    # Broadcast to current_user unread notifications count.
    MarkAsReadChannel.broadcast_to self,
    unread_notifications_count: notifications.unread_count
  end

private

  # Setter
  def set_slug
    self.slug = username.parameterize
  end

  # Reassign recipes and categories to admin before deletion
  def reassign_content_to_admin
    admin = User.find_by(email: ENV.fetch("SITE_ADMIN", nil))
    return unless admin && admin != self

    recipes.update_all(user_id: admin.id)
    categories.update_all(user_id: admin.id)
  end

  def self.receive_notification_type(notifiable)
    case notifiable.class.name
    when "Recipe"
      :recipe_created
    when "RecipeImage"
      :image_uploaded
    when "Review"
      :review_created
    when "Relationship"
      :follows_you
    when "Favoritism"
      :recipe_favored
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    if params[:body].present?
      return redirect_to root_path
    end
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [ :edit, :update, :log_in ]
  before_action :set_user, only: [ :show, :edit, :update, :destroy, :log_in, :followers, :following ]
  before_action :remove_avatar, only: [ :update ]
  before_action :deny_access!,
  unless: -> { is_author?(@user) }, only: [ :edit, :update ]

  def index
    @users = User.includes(:info, [ avatar_attachment: :blob ]).all
    @show_info_body = true
  end

  def show
  end

  def edit
  end

  def update
    @user.avatar.attach(user_params[:avatar]) if user_params[:avatar]

    respond_to do |format|
      if user_params && @user.update(user_params)
        format.html { redirect_to @user, notice: "Avatar was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if is_site_admin? && !user_is_site_admin?(@user)
      @user.destroy
      respond_to do |format|
        format.turbo_stream {
          render turbo_stream: turbo_stream.remove(helpers.dom_id(@user))
        }
        format.html {
          redirect_to users_url,
          notice: "User was successfully destroyed.",
          status: 303
        }
        format.json { head :no_content }
      end
    end
  end

  def log_in
    redirect_to @user
  end

  def followers
  end

  def following
  end

private

  def set_user
    @user = User.find_by(slug: params[:id])
  end

  def user_params
    params.require(:user).permit(:avatar, :remove_avatar,
      info_attributes: [ :id, :body, :_destroy ])
  end

  def remove_avatar
    @user.avatar.purge_later if user_params[:remove_avatar] == "1"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def is_author?(user)
    user == current_user
  end

  def is_site_admin?
    @is_site_admin ||=
      if user_signed_in? && current_user.email == ENV.fetch("SITE_ADMIN", false)
        true
      else
        false
      end
  end

  def user_is_site_admin?(user)
    if user_signed_in? && user.email == ENV.fetch("SITE_ADMIN", false)
      true
    else
      false
    end
  end
end

app/views/users/_follow_header.html.haml
.row
  .col-12
    .callout-transparent
      .center-text
        %h1.no-background= user.username
        = render 'users/profile_stats', user: user, size: 150
        = render 'relationships/form', user: user

app/views/users/_form.html.haml
= form_with model: user, local: true, multipart: true do |f|
  = render 'notifications/error_messages', object: f.object
  .row.mb-3
    .col-md-6
      = f.label :avatar, class: "form-label", for: "avatarUser"
      = f.file_field :avatar, direct_upload: true,
      accept: 'image/png,image/gif,image/jpeg', id: "avatarUser",
      class: "form-control"
  .row
    .col-md-4.mb-3
      - if f.object.avatar.attached?
        .img-thumbnail= image_tag avatar_image(f.object.avatar, 800)
        .row
          .col-12
            .form-check
              = f.check_box :remove_avatar, id: 'user_remove_image',
              class: "form-check-input"
              = f.label :remove_avatar, for: 'user_remove_image',
              class: "form-check-label"
      - else
        %i.fas.fa-user.default-avatar-300
    .col-md-8.mb-3
      = f.fields_for :info do |info_f|
        = info_f.label :body, class: "form-label", for: "infoUser"
        = info_f.text_area :body, rows: 12, id: "infoUser", class: "form-control"
  .row.mb-3
    .col-12
      = f.submit class: 'btn btn-primary'

app/views/users/_profile_stats.html.haml
= link_to user, class: 'black-text profile-stats-avatar' do
  - if user.avatar.attached?
    = image_tag avatar_image(user.avatar, size), class: 'img-thumbnail'
  - else
    %i.fas.fa-user{class: "default-avatar-#{size} img-thumbnail hide-on-print"}

.hide-on-print.profile-stats{id: "profile_stats_#{user.id}"}
  = link_to followers_user_path(user), class: 'stat' do
    %span{id: "followers_count_#{user.id}"}
      = user.followers.count
    followers
  = link_to following_user_path(user), class: 'stat' do
    %span{id: "following_count_#{user.id}"}
      = user.following.count
    following

app/views/users/_user.html.haml
= turbo_frame_tag dom_id(user) do
  %hr/
  .row
    .col-8.col-md-9.col-lg-9
      .mb-3
        = link_to user, class: "black-text", data: { turbo: false } do
          - if user.avatar.attached?
            = image_tag avatar_image(user.avatar, 50), class: 'img-thumbnail'
          - else
            %i.fas.fa-user.default-avatar-50
          %b= user.username
          - if is_site_admin?
            = user.email
          %br/
          = link_to user_path(user, anchor: 'submitted'), data: { turbo: false } do
            Submitted:
            = user.recipes.by_published.count
          = link_to user_path(user, anchor: 'favorites'), class: "ps-3", data: { turbo: false } do
            Favorites:
            = user.favorite_recipes.count
          - if is_site_admin?
            = link_to user_path(user, anchor: "drafts"), class: "ps-3", data: { turbo: false } do
              Drafts:
              = user.recipes.by_unpublished.count

    .col-4.col-md-3.col-lg-3
      .mb-3
        = render 'relationships/form', user: user

  .row
    .col-12.mb-3
      .autolinks= simple_format(truncate(user.info.body, length: 120))
  - if is_site_admin? && !user_is_site_admin?(user)
    .col-12.mb-3
      = link_to "Permanently Delete User", user_path(user),
      class: "btn btn-danger btn-sm",
      data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }

app/views/users/edit.html.haml
- provide(:title, 'Edit Profile')

.row
  .col-12
    %h1 About you
    = render 'form', user: @user
.row
  .col-12
    %ul.nav-links
      %li= link_to 'Back', @user

app/views/users/followers.html.haml
- provide :title, 'Followers'

.row
  .col-12.col-lg-5
    = render 'users/follow_header', user: @user
  .col-12.col-lg-7
    %h3 Followers
    .d-flex.flex-column.user-list
      = render @user.followers

app/views/users/following.html.haml
- provide :title, 'Following'

.row
  .col-12.col-lg-5
    = render 'users/follow_header', user: @user
  .col-12.col-lg-7
    %h3 Following
    .d-flex.flex-column.user-list
      = render @user.following

app/views/users/index.html.haml
- provide :title, 'The Cooks'

.row
  .col-12
    %h1 The Cooks
    .flex-d.flex-column.user-list
      = render @users

app/views/users/show.html.haml
- provide :title, 'The Cook'

.row
  .col-12
    = link_to choice_recipes_path, class: 'float-end btn btn-danger mb-3' do
      %i.fa.fa-plus-circle
      Add a recipe
.row
  .col-12
    .callout-transparent
      - if is_author?(@user)
        .row
          .col-12
            = link_to edit_user_path(@user), class: "float-end" do
              %i.fas.fa-edit
              Edit about you
      .row
        .col-12
          .center-text
            %h1.no-background #{@user.username}'s Cookbook
      .row
        .col-md-5.col-lg-3
          .center-text
            = render 'users/profile_stats', user: @user, size: 150
        .col-md-7.col-lg-9
          .center-on-md
            .mb-3
              = render 'relationships/form', user: @user
            .mb-3
              = link_to user_path(@user, anchor: 'submitted') do
                Submitted:
                = @user.recipes.by_published.count
              %br/
              = link_to user_path(@user, anchor: 'favorites') do
                Favorites:
                = @user.favorite_recipes.count
          .autolinks= simple_format(@user.info.body) if @user.info
- if @user == current_user && @user.recipes.by_unpublished.any? || is_site_admin? && @user.recipes.by_unpublished.any?
  .row
    .col-12
      %h3#drafts Unpublished Drafts
      .row
        = render @user.recipes.by_unpublished
- if @user.recipes.by_published.any?
  .row
    .col-12
      %h3#submitted Submitted Recipes
      .row
        = render @user.recipes.by_published
- if @user.favorite_recipes.any?
  .row
    .col-12
      %h3#favorites Favorites
      .row
        = render @user.favorite_recipes