config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process for Passenger Standalone.
  mount ActionCable.server => "/cable"

  root "recipes#index"

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :recipes, only: [ :index, :new, :create ] do
    collection do
      get :search
      post :import
      get :choice
      get "import_status/:id", action: :import_status, as: :import_status
    end
  end

  scope "/recipes/:username", as: :user, controller: :recipes do
    resources :recipes, only: [ :show, :edit, :update, :destroy ], path: "", param: :slug do
      resources :reviews, only: [ :show, :create, :edit, :update, :destroy ]
      resources :recipe_images, only: [ :new, :create, :destroy ]
      member do
        get :log_in
        get :likes
      end
    end
  end

  resources :categories do
    collection do
      get :more
    end
  end

  resources :users, only: [ :index, :show, :edit, :update, :destroy ] do
    member do
      get :log_in
      get :followers
      get :following
    end
  end

  resources :favoritisms, only: [ :create, :destroy ]

  resources :relationships, only: [ :create, :destroy ]

  resources :notifications, only: [ :index ] do
    collection do
      patch :mark_as_read
      get :settings
      patch :update_settings
    end
  end

  resources :push_subscriptions, only: [ :create, :destroy ] do
    collection do
      get :vapid_public_key
    end
  end

  get "sitemap.xml", to: "sites#sitemap", format: :xml

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe_image.rb
class RecipeImage < ApplicationRecord
  after_commit on: [ :create ] do
    NotifiyUsersJob.perform_later(self)
  end

  has_many :notifications, as: :notifiable, dependent: :destroy

  belongs_to :recipe, touch: true
  belongs_to :user

  has_one_attached :image, dependent: :purge_later

  # Always show the first image then order the rest from newest to oldest.
  # [1, 2, 3, 4] becomes [1, 4, 3, 2]
  scope :by_original_first, -> { self.rotate(1).reverse }
end

app/controllers/recipe_images_controller.rb
class RecipeImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe
  rescue_from ActionController::ParameterMissing, with: :no_image_uploaded


  def new
    @recipe_image = @recipe.recipe_images.build
  end

  def create
    @recipe_image = @recipe.recipe_images.build(recipe_image_params)
    @recipe_image.user = current_user

    respond_to do |format|
      if @recipe_image.save
        format.html { redirect_to new_user_recipe_recipe_image_path(@recipe.user.slug, @recipe.slug),
          notice: "Images were successfully updated." }
        format.json { render :new, status: :ok, location: new_user_recipe_recipe_image_path(@recipe.user.slug, @recipe.slug) }
      else
        format.html { render :new }
        format.json { render json: @recipe_image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe_image = @recipe.recipe_images.find_by(id: params[:id])
    if is_author?(@recipe.user) || is_author?(@recipe_image.user)
      @recipe_image.destroy
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove("recipe_image_thumb_#{@recipe_image.id}") }
        format.html {
          redirect_to new_user_recipe_recipe_image_path(@recipe.user.slug, @recipe.slug),
          notice: "Image was successfully removed."
        }
        format.json { head :no_content }
      end
    end
  end

private

  def set_recipe
    user = User.find_by!(slug: params[:username])
    @recipe = user.recipes.find_by!(slug: params[:recipe_slug])
  end

  def recipe_image_params
    params.require(:recipe_image).permit(:image)
  end

  def no_image_uploaded
    redirect_to new_user_recipe_recipe_image_path(@recipe.user.slug, @recipe.slug), notice: "No image uploaded."
  end
end

app/views/recipe_images/_recipe_image.html.haml
#recipe_image_container
  .recipe_image_card
    .recipe_image_uploader.hide-on-print
      = link_to recipe_image.user, data: { turbo_frame: "_top" } do
        Uploaded by:
        %b= recipe_image.user.username
    .recipe_image_image
      = link_to rails_blob_path recipe_image.image,
      class: 'max-image-height', data: { turbo_frame: "_top" } do
        = image_tag large_image(recipe_image.image), class: 'img-thumbnail'

app/views/recipe_images/new.html.haml
= form_with model: @recipe_image, url: user_recipe_recipe_images_path(@recipe.user.slug, @recipe.slug), local: true, multipart: true do |f|
  .row
    .col-md-6.col-12
      .callout-transparent
        = render 'notifications/error_messages', object: f.object
        .mb-3
          = f.label :image, 'Upload image', class: "form-label", for: "image_file_field"
          .small.italic
            Landscape for best results.
            %br/
            Don't leave page until upload is complete.
          = f.file_field :image, direct_upload: true, id: "image_file_field",
          accept: 'image/png,image/gif,image/jpeg', class: "form-control"
        = f.submit 'Upload Image', class: 'btn btn-primary'
      %p= link_to 'Finished Editing', user_recipe_path(@recipe.user.slug, @recipe.slug), class: 'btn btn-warning'
  .row
    - if @recipe.recipe_images.any?
      - @recipe.recipe_images.by_original_first.each do |recipe_image|
        - if recipe_image.image.attached?
          .col-12.col-md-4.col-lg-3
            .mb-3{id: "recipe_image_thumb_#{recipe_image.id}"}
              = link_to recipe_image.user do
                Uploaded by:
                %b= recipe_image.user.username
              .img-thumbnail
                = image_tag large_image(recipe_image.image), class: "pb-1"
                - if is_author?(@recipe.user) || is_author?(recipe_image.user)
                  %br/
                  .center-text
                    = link_to 'Remove Image', user_recipe_recipe_image_path(@recipe.user.slug, @recipe.slug, id: recipe_image.id),
                    class: 'btn btn-danger btn-small',
                    data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }